INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (118, '追光者', 242104, '八年过去了，郑爽还是如八年前的流星雨一样纯洁如外表，干净而亲切，就如这歌一样清新的声音仿佛把立夏的一切描述的淋漓尽致。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (119, '80000 （Prod.By DROYC）', 325911, '谢谢各位这么喜欢我的这首歌，突然被下线我也懵了，赶快跑回家上传，新版本年底之前我一定会做出来，承蒙各位厚爱小巴抱拳了，rapper虽然要有态度，可是还是要对各位爱听歌的老铁保持respect，持续关注。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (120, '文爱', 104482, '网恋不算异地恋 那叫臆想恋 望周知');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (121, '红昭愿', 85276, '正在回你评论的。。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (122, '言不由衷', 5374, '小时候我们词不达意，长大了我们言不由衷。徐佳莹第五张专辑《心里学》12.27正式发行，12.6首波主打《言不由衷》MV全球首播！');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (123, '像风一样', 153038, '像风行了八千里   不问归期');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (124, '打上花火', 52808, '疯狂支持，去年陪你看你的名字的他，今年还在你的身边吗？动画电影《升起的烟花，从下面看？还是从侧面看？》改编自岩井俊二导演的同名电视短片，由新房昭之担任纲总导演，影片将于8月18号在日本上映，9月15日在台湾上映，10月在香港上映，大陆有望引进。相约去电影院看吧');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (125, '9420', 93852, '谢谢大家的支持，我会更加努力的[憨笑]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (126, '连名带姓', 5338, '阿妹刚刚ins直播的时候说：帮我转告杰伦，这首歌非常好听，也谢谢赛琳娜，辛苦她了～');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (127, 'Panama', 229309, '几类几类，几类几类，要类噶，美类美类，美类美类，比里买但，把住几内几内，猜次哦打扮，军吗的本打，把的来耐求妈妈，丹家，呀来把索，努力地理地理，怒马度西，度色噶，啊里给里给里，伦家，美噶，桑五，巨累巨累，A雷马，把你蹦蹦，怒马把你给，唉唉，唉唉， 唉唉');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (128, '带你去旅行', 492137, '帮你算了一下。你这次旅游估计要花20多万');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (129, '我们不一样', 101711, '马上就要前赴西藏去当兵，希望我能完完整整的回来，因为我的爸爸妈妈还在等我回家，爱你们❤');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (130, '广东十年爱情故事', 45141, '我来啦，网易音乐人刚刚审核通过，我慢慢把其他歌更新上来，感谢[拜]各位老大[呲牙]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (131, '远走高飞', 372267, '曾经梦想仗剑走天涯，后来作业太多就没去!');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (132, '再也没有', 227895, '年度最佳虐心[心碎]再也没有说我放不下你.');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (133, '背过手', 31632, '无奈的请背过手;无辜的人放了手。\n无奈了请放下手;无耻的人请伸出手。\n手，不知不觉间刻画着我们生命中的一切…月台上的挥别…父母的拥抱…看似缈小，实则强大…背过手，含了多少泪水，含了多少无奈…');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (134, 'Remember Me (Dúo) ', 32310, '“可这首歌，我不是写给世界的，我是写给我的女儿coco的”');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (135, 'COSMOS', 10668, '她的音乐不止有《奇妙能力歌》的小清新，她还有《正趣果上果》的调皮，《历历万乡》的潇洒，《性空山》的慷慨。她用让人中毒太深的嗓音，唱尽少年子弟一腔冷热和万般唏嘘。与其说她是个特立独行拒绝标签的民谣歌手，倒不如说她是个非常自我的音乐人，所以，她不写民谣了，才更像她。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (136, '说散就散', 460307, '路过你楼下，车停下来了。 你给我发了短信：我结婚了，不要再来骚扰我！ 我没回你短信，因为我用自行车接送你三年，而他用奥迪送了你三回，于是你们结婚了。去你楼下，只是三年的习惯。我很庆幸，这么早的看透你。 昨天你打我电话：他有外遇了，我怎么办？ 我说：你有外遇的时候，想到我怎么办吗？');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (137, '我多喜欢你，你会知道', 47732, '“你觉得胡染染漂亮吗？”“漂亮。”“多漂亮？”“比你漂亮。”我说:“你觉得她的漂亮足够让男人原谅她的过去吗？”“对我来说不够。” “那如果是我的话，你会不会原谅？”江辰沉默了有一个世纪那么久，然后说:“会”。“为什么？不是说我没有她漂亮？”他吻了一下我的额头，“因为够爱。”');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (138, 'Perfect Duet (with Beyoncé)', 33879, 'Promise(承诺)、Earnest(诚挚)、Respect(尊重)、Forgiveness(宽容)、Enioy(享受)、Cherish(珍惜)、Trust(信任)是破译幸福Perfect的七个密码。还有21天考研，我已经有钥匙了，考完试你来当我的锁吧[爱心]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (139, '蝴蝶的时间', 52819, '在这个网络飞速发展的时代。当你看倦了娱乐圈五花八门的头条绯闻。你就会发现，像许嵩这种纯粹做音乐的音乐人是多么可贵。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (140, '想把你留在这里', 24428, '为JonyJ爆灯 真心不怕辜负 誓言不怕美人迟了暮 是诗人没错了');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (141, '退', 22669, '往事今非昔比 回忆如一滩泥');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (142, 'Despacito (Remix)', 338905, '旁边一妹子说 Justin声音一出来她就高潮了');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (143, 'Shape of You', 351584, '麻烦催一下你闺蜜泰勒小姐谢谢');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (144, 'Psycho (Pt. 2)', 37320, '我渴望的不是一个肉体，不是一起做乐，我渴望有那么一个灵魂，可以看透我放纵下的清澈 牵起我的手，提醒我“你看远处的山多么飘渺不真实，停下来，让我拯救你”。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (145, '童话镇', 591487, '对了~平时每晚八点半，在斗鱼67373直播间可以看到我。不一定在唱歌，也可能在讲段子[吐舌]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (146, '成都', 583182, '你真的红了 很开心 内场票也可以卖到1000+ 虽然以前50就能听你的livehouse 越来越听不起你的演唱会 不过没关系 我会努力变得跟你一样好 民谣不应该穷 以前你吃过的苦都是值得的 难过的日子都是你陪我一起过的 你说你是个普通人 想要买房结婚 我知道 愿你有酒有肉有姑娘 #赵雷');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (147, '全部都是你', 403500, '你们这些用网易云的女孩子一定很可爱吧');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (148, 'OKAY', 14624, '妹子们觉得这首胸肌好听吗[大哭]\n你们还okay吗[奸笑]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (149, '在人间', 240404, '<女方结婚，男的尾行了7km，最终被发现，女的发短信：对不起，别送了>看了这个段子过来的右上角');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (150, '过客', 29500, '总有一天你会遇到你真正喜欢的人 和他的女朋友');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (151, '岁月神偷', 246276, '上个月你结婚了，新娘和你很般配，嗯。你从当年的小男生长成了大男孩。亲她的时候，我突然想起高二那个中午，你偷亲我，你不知道的是，其实当时我没有睡着。现在我也有了女朋友，准备明年结婚了，祝彼此幸福。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (152, '多想留在你身边', 25525, '你给妈妈发短信 妈妈不回你 \n你一般不会心慌\n你给对象发短信 对象不回你 \n你也许会心慌 为什么 \n根本原因是 你确定你妈爱你 而不确定你对象爱不爱你 \n只有不确定的东西才会让人患得患失');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (153, '醉赤壁', 48537, '我暗恋高中一个男生 他是我们班的音乐委员 那次他教我们唱这首歌 我笑到不行 可是还是很喜欢他吧 有一天站着唱歌的时候 我一直盯着他的背 然后他突然转过来 我吓得坐到了椅子上 [流泪] 好想他 现在做梦还经常梦见他 而他在西藏林芝默默守卫边疆 我在繁华的上海流浪 我不能嫁给他了');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (154, '世界上的另一个我', 89237, '上一秒我在高数课捡笔  下一秒我就听不懂讲到哪里');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (155, '安和桥', 351662, '我想我妈妈了，好希望自己还是那个17岁的少年，每天晚自习在楼下喊，妈，我回来了，然后她就下楼给我开门。可是我妈已经离开我10年了！感觉从她走得那天起，我再也没长大过。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (156, 'Faded', 206104, 'faded是fade的过去式，过去的过去已经过去了，唯有静观现在的生活，不以物喜，不以己悲。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (157, 'So Far Away', 16791, '毕业后\n你去了英国留学，学费三十万一年\n我回到家乡上班，工资三千块一月\n确实，so far away');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (158, '理想三旬', 420029, '爷爷病重，考研失败，骑士也没夺冠，今年似乎一切都不顺利。明天就要离校，辗转难眠，我的亲人和理想你们慢些走[皱眉]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (159, 'Nevada', 179667, '在优酷上看一个十五秒的视频之后的网游广告的BGM是这首，可惜广告不能暂停。错过之后我为了找这音乐把这段视频反复播了20次（当然每次都快进到快结束的地方）才终于又看到同一个广告，赶紧拿出准备好的手机来听歌识曲……终于找到你。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (160, '告白气球', 508189, '刚刚我把这首歌分享给我喜欢的女生向她告白成功了！！！');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (161, 'I Am You', 365614, '七年前喜欢的人因为乳腺癌去世了，很坚强的女强人，教会了我很多东西，七年之后，我发现自己正变得越来越像她，她的思维方式，她的言谈举止，她希望我成为的那种男人。我现在可以理解为什么说有的人会永远活在心里了，这可能就是我记住她的一种方式。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (162, '姗姗', 15014, '姗姗像你，秀骨姗姗。\n你像姗姗，姗姗来迟。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (163, '刚好遇见你', 295579, '李玉刚合唱团已上线，女高音李玉刚、女低音李玉刚、男高音李玉刚、男低音李玉刚[大笑][大笑][大笑]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (164, '最美情侣', 150556, '叔叔阿姨，我能在济南买的起房子了，把她还给我吧，我真的离不开她。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (165, 'Dream It Possible', 288428, '看到华为的广告发现的，愿我们名族企业越来越棒，留学的日子在路边看到华为的广告，莫名会有一些小激动');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (166, '小半', 454549, '我的心借了你的光是明是暗');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (167, '爱的就是你', 45561, '不好意思，今天我喜欢这首歌✔');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (168, '骆驼', 84009, '我只知道老薛做音乐从心，不从众。我愿与你 在无知世界 漂泊探索');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (169, '可乐', 331405, '夜深时点开相册浏览女友的照片，正好播这首歌，慢慢的眼泪流了下来，原来一首歌还可以让我流不出来的眼泪重新冲了出来。高考完第三天出车祸了，抢救两天两夜人走了，说好的来找我呢。你怎么能走了。[心碎]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (170, 'How Long', 36437, '一波三折我猹的How Long<蜜汁:多长>终于上线了，据猹说这首歌讲的是个故事，爱情故事？中间的三段旋律太棒了，不由自主的就哼起来了，这小调贼爽~~~喔~~~喔~~~喔~~~');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (171, '九张机', 128504, '月七果然比宇文玥有出息[奸笑]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (172, '短发', 41021, '短发姑娘，我要陪你长长[呲牙][呲牙]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (173, 'Something Just Like This', 127042, 'Coldplay的歌曲总是这么触动人心，马丁温暖的声音里似乎蕴藏着满天星辰！有生之年一定要做的事情就是去看一次酷玩的演唱会！！');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (174, '夜来妖', 11534, '陈冠希在纽约大学演讲上说：“我出生在加拿大，但你看看我的长相，我是中国人”，“我相信有一天，我们（中国）会成为世界上最有影响力最强大的国家”。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (175, 'Зая', 6249, '日推第一[钟情]  右上角');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (176, 'Havana', 48190, '网易的玩家有一个惯性，明明这首歌超级好听，但就是不告诉小伙伴，偶尔会想尽办法的让他们听到，得到他们的认可，但就是不告诉他们歌曲名字。到了后来，自己喜欢的那首歌曲，突然火了起来，好多人也知道了，开始听了。就感觉自己的宝藏被盗取了，有一种说不出的委屈。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (177, '老街', 94604, '一个人在去南京的火车上，去看妈妈。单曲循环这首歌，哭得不能自已。越长大老街渐渐成了回忆，而父母也老了。以前总觉得他们像金刚，什么事都可以帮我们抗，简直无所不能，所以肆无忌惮。这次妈妈做手术我真得好害怕，总要亲眼看看才放心。希望妈妈早日康复，一切都好起来。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (178, '骗自己PT.2 (Remix-下酒菜)', 129419, '别骗自己了 多骗骗别人');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (179, 'Wicked Wonderland', 87067, '这唢呐吹的不错');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (180, 'All Falls Down', 46078, 'Alan Walker新歌深夜上线！另外Alan Walker年仅20岁就取得了百大DJ 17的名次，前途可谓不可限量啊！');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (181, 'Closer', 335930, '人家15岁就会打碟了，我15岁我妈还在打我');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (182, 'Seve', 127984, '斯瓦西里语（kiswahili），属于班图语族，是非洲语言当中使用人口最多的一种（5500多万人），是坦桑尼亚的唯一官方语言，肯尼亚和刚果民主共和国的国家语言之一，和赞比亚、马拉维、布隆迪、卢旺达、乌干达、莫桑比克等国家的重要交际语');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (183, '别', 249028, '好久不见，歌手 薛之谦。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (184, '凉凉', 87725, '网易云大哥把凉凉原版版权拿来吧！！！！');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (185, '七月上', 287642, '我的高中同学！！！！！！！[强][强][强][强][强][强][强][强]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (186, '男孩', 59016, '有多少在线等梁博原版的');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (187, '做我的猫', 19937, '我就是喜欢猫 因为它有个性还非常专一 不管你有钱没钱 好看还是不好看 它就是不喜欢你');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (188, 'Heartbeat (Nightcore) [PØRPEL Remix]', 10168, '你就这样一路蹦蹦跳跳  撒着小星星跑到我心里啦——Better With You');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (189, '天后', 57336, '欢迎收听《备胎之王的心声》');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (190, '红色高跟鞋', 256707, '“像被子里的舒服，又像风捉摸不住”不是屁是什么？[呆]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (191, '走心小卖家', 40837, '说实话 我做微商一共卖出去四双鞋');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (192, '遇见', 163432, '这歌我听了十年……好可怕的数字……');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (193, 'Victory', 314628, '我不能保证你们每个人都能活下来，但世界需要你们。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (194, '房间', 256932, '初恋今天结婚了，我去了，没有尴尬，没有扭捏，大大方方的就去了，她还是和当年我看上她时一样漂亮有气质，一样那么温柔 那么可爱。但是好奇怪我没有妒忌和不愉快，那一刻终于发现，曾经爱她是真的，现在的祝福也是真的。原来真的有由衷的祝福，感谢她那么优秀，我的青春没白过');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (195, '平凡之路', 121886, '去年高考完徒步搭车 川滇 滇藏 青藏线\n一个半月\n在旅途结束的西宁看了电影\n回来单曲循环\n16岁便独自搭车川藏线\n作为妹子我也真算得上异类\n平时不敢听它 一听就想哭想背包出发\n现在大一 前几天憋坏了\n逃课骑摩托车去了趟川西\n奔驰在一望无际大草原柏油公路\n单曲循环 平凡之路\n放声大唱\n你不知道有多自由');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (196, '11887', 10580, '过去很少写开心的歌，但今天已不再是昨天。[爱心]人生苦短，开心要紧。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (197, '致姗姗来迟的你 ', 172846, '@网易云音乐 必须搞定林宥嘉五月天版权！！必须！必须！必须！！！！');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (198, '夜空中最亮的星', 87788, '音乐是味道，听着这首歌仿佛能够闻到大学的冬天');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (199, 'Oops', 112303, '寒假相亲了三次 最后一次 真的对了[可爱]说的每一句话都能接得住 完全不用担心尴尬 哪怕困得睁不开眼 还是想聊天 第一次见 害羞的不敢看[憨笑]这歌好听的我要分享给他！祝我们幸福吧[爱心]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (200, '独家记忆', 77269, '今天，我应约去见你，去之前试了两个小时衣服，甚至连内衣都换成配套。见到你那一刻，并没有想象中的失望或者激动，只觉得本来小小的心突然被扩张得好大好大。七年了，I`ve never stopped loving you，我从未停止爱你。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (201, '老大', 200344, '没男票是有原因的 听这种歌 根本稳不住');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (202, 'Five Hundred Miles', 295030, '好想哭，没有女朋友');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (203, '春风十里', 276543, '春风十里 五十里 一百里 体测八百米 海底两万里 德芙巧克力 香草味八喜 可可布朗尼 榴莲菠萝蜜 芝士玉米粒 鸡汁土豆泥 黑椒牛里脊 黄焖辣子鸡 红烧排骨酱醋鱼 不如你 全都不如你 ');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (204, '白山茶', 80178, '2个月前女朋友在快手上听这首歌，我当时觉得歌词很质朴很有感觉。现在我们分手了，我才发现我就是那朵白山茶，而她却选择了红玫瑰。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (205, '遥远的歌', 16908, '你说，大家来参加升旗仪式，是不是都为了能光明正大地偷看一眼平时不容易见到、或者能见到却不敢明目张胆注视的某个人啊？有时候课间操和升旗仪式是很多人最为期待的。乌泱泱的人海中，他们总是能寻寻觅觅地将目光定位到某个人身上，将冗长无趣的仪式变成一场不足为外人道也的独家记忆。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (206, '钟无艳', 184624, '男不听七友，女不听钟无艳[流感]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (207, 'Sugar', 260388, '美国某知名乐队沦落到婚礼现场蹭吃蹭喝');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (208, '春风吹', 24182, '吃饭录音薛凯琪');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (209, '你根本不懂', 4546, '我建了个小号 资料和你一模一样 想和你说话的时候 我就给小号发几句 然后登小号 回自己几句。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (210, '晴天', 537812, '高一听的，那时候遇到了孩儿他妈，然后就这么幸福下来了');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (211, 'BOOM', 98945, '走路不能听，拽的跟二五八万似的');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (212, 'Samsara', 16238, '在班里用班班通听这首电音，音量调到最大，全班炸起来。校长过来了，我把音乐暂停了，校长说了一句不要暂停，到高潮了。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (213, 'See You Again (feat. Charlie Puth)', 516834, '就在保罗沃克去世前13天，我高中最好的一个兄弟也因为意外去世了。曾经一起在寝室看了速度1，之后一起看了速度5速度6。曾经也同样挚爱速度与激情。今天去看了第七部，保罗沃克不在了。我兄弟也不在了。当听到这首see you again真的眼眶湿润了。献给保罗沃克，献给我的兄弟！');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (214, 'Es rappelt im Karton', 287744, '卧槽，终于撞到了，舍友一个咪咪咪咪，一个耶耶耶耶耶耶，一个呱呱呱呱，我终于也有个铃声了');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (215, '不找了', 335811, '我觉得这首歌对我的ID有莫大的恶意[皱眉]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (216, '青柠', 20200, '为什么我吃的每个青柠都是甜的，难得是我的味蕾出了问题吗？哦！我知道为什么了，因为是你给的');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (217, '追梦赤子心', 249844, '刘翔是唯一一个在直线跑道上真正打败黑人的运动员，甚至创造了连白人都没做到的记录。刘翔参加了48次世界大赛，36次冠军，6次亚军，3次季军，然而有些人却只记得他退赛2次 ');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (218, 'The Spectre', 50892, 'Alan walker 原来的这首《The Spectre》是首纯音乐，没想到融入男声之后居然和《Faded》融入女声有异曲同工之妙。好听！');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (219, '当你', 87973, '高中和同桌一起听林俊杰的歌，过去整整十年了，今年终于和同桌结婚了，我的初恋，我的一生，爱你老公[色]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (220, 'Counting Stars', 248311, '给翻译大神跪了！这功底太深！');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (221, '我要你', 179090, '周铁南跪下那一刻比他死了还让我难受');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (222, '你瞒我瞒', 71385, '今天音乐课，下节课教什么歌征集他们的意见，在都是tfboy的歌单里，班上永远不写作业的那个男孩子，居然写了你瞒我瞒。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (223, '请记住我', 7222, '毛不易的版权  一直在等');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (224, 'Beautiful Now', 89111, '全套歌词都是我上传的，包括中文[吐舌]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (225, '大鱼', 266060, '真的觉得中国人很奇怪！[撇嘴]对自己国家的文化没有任何自信  为什么好不容易中国有了不错的作品 国人就开始诋毁 说什么抄袭千与千寻，但是大鱼的故事 还有人物的背景 和千与千寻千差万别 而且都是中国自己的东西 客家土楼 山海经 凤凰 龙 还有逍遥游 这都是满满的中国风 ！');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (226, '远走高飞 (合唱版)', 35637, '一年前的我是歌手，两人因一场你走我留的踢馆赛结下缘分。过去的一年，他们被更多的人知道和喜爱，拉拉正努力地准备着自己第二次大型巡演，小文也用一张精心制作的专辑向大家展示自己过去两年的音乐之旅。今天他们一起用这首歌告诉我们，如果还有梦就追，至少不会遗憾后悔。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (227, 'Shape of You', 44930, '想必从b站来的绅士不止我一个');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (228, '开不了口', 65827, '大学最好的朋友，也是唯一的基友，背着我谈了女朋友，唉。。。不提也罢');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (229, 'Freaks (Radio Edit)', 186045, '恭喜你发现万恶之源');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (230, '啷个哩个啷', 103337, '所以不要天天自虐喊着单身狗 你也可以当个高傲的大犀牛 享受单身生活[憨笑]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (231, '再见', 42837, '嘿秦洋 我的初中同学❤看见你一点点进步实现了自己的梦 为你开心为你祈祷.');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (232, '就是爱你', 37524, '每次听完都很有恋爱的感觉 醒来发现 尼玛还是单身 ');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (233, '普通朋友', 4907, '马克和田野离婚后学会了当一个照顾人的老师，王小米作为一个90后小女孩，从邱枫哪里学会了做一个真正的女孩，而不是当一个大姐姐。很多人都是这样，经历过才能遇到自己内心想要的人，所以大家都是幸福的，没有什么遗憾，都是感激。愿所有网易云的朋友能早早明白自己内心想要的那个人！');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (234, 'I Just Wanna Run', 257257, '自从用了网易听歌不看评论难受');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (235, '易燃易爆炸', 242590, '觉得这首歌的歌名应该叫“你TM到底要我怎样”');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (236, '偏爱', 182763, '后来别人告诉我这是个女生唱的。。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (237, '不要说话', 96120, '一听到“我以为你懂的每当我看着你”就难受。高中我喜欢的一个女生就总是那样看着我。我们关系挺好的，有点暧昧，甚至有共同的秘密。我以为她也喜欢我。过了三个学期，她和她以前初中的男的同班同学走得很近，然后我着急了，向她表白，才明白一直都是我错了。我以为我懂她，也以为她懂我——');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (238, '是梦吧', 33174, '知乎上有个问题   “突然不喜欢一个人，是什么感觉？” 有个回答是 “他本来浑身是光。有那么一瞬间，突然就黯淡了，成为宇宙里一颗尘埃。我努力回想起他全身是光的样子，却怎么也想不起来。后来发现，那是第一次见到他时，我眼里的光。” ​​​');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (239, '遗憾', 62720, '早日回来好好做音乐[爱心]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (240, '风的季节', 48725, '看不懂评论的就我一个人吗[大哭]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (241, '凉城', 221705, '我在这里 等你们很久');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (242, 'Hello', 278188, '从此多了一个流派：电萌');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (243, '不用去猜', 196846, '很多时候生活中的意外跟惊喜总是很突然 ，预测是很没有意义的事，不想去猜结果，过好每一个当下，感谢所有摸黑的一路上亮起的灯 ，当我发光的时候希望也可以为你照亮');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (244, '其实都没有', 103012, '耳机里面是喜欢但还不会唱的歌 手机屏幕上的照片是喜欢但还没在一起的人');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (245, '牵丝戏', 120882, '新歌首发，邀请阿姐惊艳登场演绎戏腔。这首歌也带有一些魑魅动情的意思，不过比锦鲤抄中的完美爱情要多了一些现实感哈～');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (246, 'Crystal Snow', 3378, '这是RM以最后一次rap monster的身份来跟大家见面');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (247, '只只', 4056, '耳机里还放着我们共同喜欢的歌 手机屏幕上照片里的人还是很喜欢 但永远不会在一起了 我一直很想你 在白天发呆的时候 在夜里不眠的时候 偶尔也喜欢别人 但那是在他们像你的时候');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (248, '儿子，我是你爸爸', 56710, '总感觉听一遍就吃一回亏。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (249, 'Uptown Funk', 159285, '昨天有人学着这个MV走路，我把他打了4次');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (250, '椿', 77872, '等有资格结婚了，我要嫁给一个很平易近人的男人，他没有大大的啤酒肚，没有地中海似的大光头，没有鸡毛蒜皮都计较的小心眼，也没有莫名其妙就爆发的坏脾气，他要喜欢运动，充满男子气，他要喜欢唱歌就算走调让我哭笑不得，他要捧着我的脸说娶到你真是我的福气.');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (251, '借我', 97270, '杀死庸碌的情怀 人怦然心动如往昔 纣王老胡到此一游[憨笑]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (252, 'Intro', 273360, '这首音乐全长2分8秒');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (253, '水星记', 46117, '“作为离太阳最近的一颗行星，水星无法脱离自己的轨道也无法更靠近太阳，从最初的想要去靠近，到最终的以遵循原有的轨道相伴运行，借由天文的概念来喻指人与人之间亦远亦近的情感关系。”');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (254, 'Parties', 30591, '私人fm推到这首歌的都是幸运的人');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (255, '勉为其难', 128707, '为何在评论里都是千载难逢的情圣，为何在现实里都是不堪一击的烂人');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (256, 'Undress Rehearsal', 16778, '網易云是B站大軍的後援基地。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (257, 'Toca Toca (Radio Edit)', 42263, '新疆夜店金曲');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (258, 'GQ', 24841, '战斗民族养成记走错路然而不想出去了…');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (259, '心愿便利贴', 2891, '别那么懒 多听听各个版本 你就会发现最好听的在这 讲真');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (260, '全世界谁倾听你 ', 154097, '你们没有发现吗 今天的日期正反读都是今天。2016.10.2');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (261, 'Trip', 331997, '手机里全是外语音乐,朋友一看说我装逼，我真的无法解释，懂我的人请鼓励我[流泪]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (262, 'Look At Me Now', 176813, '这首歌不是神预测，而是一个努力的人得到了他应该得到的。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (263, '不为谁而作的歌', 92214, '这歌又叫做《有本事你翻唱啊》、《拒绝大合唱的歌》、《调高到唱背过气的歌》、《歌词不会哼哼过去的歌》。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (264, 'Whistle', 109820, '高中起床的起床铃声，一宿舍的室友都觉得赞。换了起床铃，他们都不起来了[呆]只好在换回去= =多么任性的室友');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (265, '有点甜', 94491, '为什么会觉得现在这年纪，喜欢听这种歌是一件很不好意思的事，噗~~~');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (266, '如我', 2686, '作词：郭顶\n作曲：郭顶\n编曲：郭顶\n演唱：刘惜君\n[爱心][爱心][爱心]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (267, '化身孤岛的鲸', 151127, '鲸落“当鲸鱼在海洋中死去，它的尸体会最终沉入海底。生物学家赋予这个过程一个名字——鲸落（Whale Fall）。一座鲸鱼的尸体可以供养整套生命系统长达百年，这是它留给大海最后的温柔。”——百度百科');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (268, '七友', 147796, '听完钟无艳看了评论过来的～');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (269, 'Legends Never Die (Alan Walker Remix)', 23599, '许多年后，faker的孩子指着10座两杯中最高的一座问faker：“为什么这个奖杯放这么高呢？”  faker：“这是你爸爸第一座亚军奖杯，很有意义的。”  孩子问：“那是爸爸要铭记失败吗？”  faker说：“不，那里面装的是你bang叔的骨灰！”');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (270, '南山南', 206178, '\"你在南方的艳阳里大雪纷飞，我在北方的寒夜里四季如春\"，这首歌深刻地点明了北方有暖气南方无暖气所导致的人民矛盾。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (271, '逝年', 128682, '这首歌会被人发现的[憨笑]当初的人呐 你们如今在哪。（等待999+）');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (272, 'Free Loop', 195003, '找不到的话，这个锅我可不背[呆]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (273, '情话微甜', 22214, '爸妈认识第一年就结了婚有了我，很多人以为他们的闪婚不会幸福，不过我现在十八岁了依然恩恩爱爱羡煞旁人。前两个月我的录取通知被妈妈查到了，当时在外面玩，爸爸很兴奋的给我打电话。“崽崽快回来！！你通知书来了！！爸爸做了一大桌好吃的！等你开饭！！全是你妈爱吃的！”');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (274, '遇到', 76341, '湘琴好像永远都不知道我有多爱她—直树');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (275, 'Hymn For The Weekend [Remix]', 89933, ' Alan：总不能老是让别人玩我的歌吧，我也要玩玩别人的歌[大笑]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (276, 'Victoria', 12279, '短短一个月，由作词谱曲编曲到录制，相较5年前的原创，《Victoria》的人声、编曲、和声、鼓点更有层次，更加立体，钢琴的伴奏更让Victoria如一首小夜曲，静谧港湾之夜，娓娓讲述，那些老街巷、维多利亚港、天星小轮、时代广场、旧笔记与脆蛋挞，还有那些年月与繁花。家，是你读千遍也不厌倦的童话。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (277, '心愿便利贴', 2510, '忙了一晚上要睡了，习惯刷下网易云，不知道怎么刷到你，从你的热门一首首往下刷，都给我乐屁了，听一首歌刚要要被感动，立马串进来别的让我调频[大哭][大哭]听到你正儿八经唱了这首歌，为什么分分钟好感动，因为找到一首能老老实实的单曲循环听了赶紧睡觉的歌了[大哭]～古耐，bgm少年[亲亲]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (278, 'The Ocean (Radio Edit)', 115050, '果断下载，发现要付费，犹豫了一下，点了红心♥️[流泪][流泪][流泪]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (279, 'BINGBIAN病变', 18747, '这是一个人人手机不离手的时代，他要回你信息早就回了。\n你苦苦等待一个答案，殊不知，不回复已经是答案了');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (280, '我喜欢上你时的内心活动', 172692, '“跟我走吧  忐忑给你 情书给你  不眠的夜给你 四月的清晨给你  雪糕的第一口给你  海底捞最后一颗鱼丸给你  手给你 怀抱给你 车票给你 跋涉给你 等待给你  钥匙给你 家给你  一腔孤勇和余生六十年 全都给你” ​​​');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (281, 'A Little Story', 203613, '女友在蛋糕店当收营员，cbd中心，黄金地段，顾客逼格都比较高的，她店长以及同事都是些颜值比较高的。他们店里每天要放音乐，上次她叫我帮下点歌，于是我就把我歌单中我喜欢的全部下了，她的同事们天天在抱怨这都什么歌啊，瞬间对他们无感，但每天都有人来问歌名，生意都好了很多，因为档次上去了啊');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (282, 'Papillon', 52556, 'mv一秒都几万块，歌居然免费听[惊恐]这么良心，你确定不入坑[奸笑]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (283, '感谢你曾来过', 92741, '有多少是日推来的[拜]感谢各位');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (284, 'Solo Dance', 49495, '这首歌名字翻译过来是叫尬舞吗？？');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (285, '小跳蛙', 220962, '这歌有毒，不要问我一个25岁的大老爷们为什么会听，你特么家住在幼儿园楼上试试[大哭]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (286, '天造地设', 3276, '依着我的背 守着你的美  \r最美的风景不过如此了吧');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (287, 'B What U Wanna B', 129805, '主要是以前这首歌总是被那种奇怪的网站冠上一个《非主流超好听音乐》《超HI超好听的英文歌》之类的名字，结果让这么好的歌曲变成好像非主流专属一样了');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (288, 'East of Eden', 85561, '美国新晋女歌手，亚利桑那州长大。喜欢冬季滑雪和足球。风格走的是轻摇滚，她的声线像带着阳光散发出的慵懒气息，带着一种随性。在国内知名度不高。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (289, 'TheStar', 57400, '哇→_→那我也来，谢谢听众老爷们捧场');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (290, '曾经的你', 81084, '高中去修掉进马桶里的手机，师傅凌乱的工作台上放着几张许巍CD,整整一下午，夏天闷热的小房间就放着许巍，而我却感觉是在远方旅行了一趟。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (291, 'Good Time', 113625, '美国春晚压轴曲《今天是个好日子》');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (292, 'Sky (Radio Edit)', 166096, '网易最近成天给我推荐这种特别燃的音乐，妹的，成天打鸡血，听得都要炸毛了！！！每次都是听着听着身上使命感越来越重，有种要去炸学校的想法，听完就正常了[大哭]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (293, '那些你很冒险的梦', 43410, '河边，一男孩向女孩表白，女孩明显想拒绝却扔了句：跳下去我就相信你，男孩一秒后落入河内，浑身湿透起来了，女孩拿纸刚想给他擦，男孩慌忙退了几步，说：我跳是因为证明曾经对你的执着，现在却后悔自己的曾经。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (294, '勇敢爱', 127977, '我51，热恋中的男朋友今年28，我比他妈妈还大1岁，可我们相爱，你们不会知道这需要多大勇气。若非亲身经历，我也不信爱情真的无关年龄。而且我还是男的。[大哭][大哭][大哭]');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (295, '只要有你', 40114, '就没人夸夸周杰的演技么');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (296, '奇妙能力歌', 27316, '我有那么多奇妙的能力，却留不住你');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (297, 'Bye Bye Bye', 134849, '高二的时候学校的广播放过这首歌，感觉太好听了，但不知道这首歌的名字，我就准备用语音搜歌，但我一掏出手机广播就出故障了，之后广播再也没放过这首歌，我用了能想到的一切方法去找这首歌，无果，两年来这首歌的旋律在我心里氤氲不去，如今，这首歌以类似歌曲的形式蹦出来了，如何让我不激动？爱网云');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (298, '儿时', 166109, '小时候五年级用没有油的圆珠笔在纸上写下自己的名字，递给我喜欢的那个女孩，然后装神弄鬼的跟她说“你拿铅笔涂一涂，你另一半的名字自然就出现，别犹豫亲上去”。我到现在还记得当她看到我名字时义无反顾告老师的样子。。。。虽然还是很漂亮，但那瞬间我觉得我的青春扑街了。');
INSERT INTO `09hot_comment` (`id`, `song_name`, `liked_count`, `content`) VALUES (299, 'Breath and Life', 199161, '[大哭][大哭]听完这首歌确实有一种“爸妈七大姑八大姨亲爱的弟弟妹妹同学朋友老师，再见，我要去拯救地球”……的感觉');
